### ISSUE TITLE
Collection facet not working

### ISSUE THREAD

**Issue by jawalsh** [Conal-Tuohy/swinburne#17]
Selecting any of the "Collection" facet items returns "0 results". See <http://swinburne-dev.luddy.indiana.edu/search/?collection=Studies+in+Song>.

**Comment by Conal-Tuohy** [comment]
The bug was a regression induced by changing the search generally from a phrase search to a key words search. In fact the values of facet fields _should_ be treated as phrases (and now they are, once again).
