### ISSUE TITLE
check figures

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/swinburne#2]
figures in the "notes on funeral" are not appearing

they need to go into the `figure` folder in this repo, in an appropriate subfolder, and we should kill off all the other newton figures, I guess 😉

**Comment by jawalsh** [comment]
Bad link in image tags, e.g., "http://10.0.0.232:8080/text/acs0000504-01/figure//swinburne/images/swinburne/acs0000504-01-003.png"

Link to problematic page: http://10.0.0.232:8080/text/acs0000504-01/

**Comment by Conal-Tuohy** [comment]
Fixed in 8d86ae53f338cc7bcd5e38f8a8e85efc1a27099b

Since the issue was about resolving URIs, I leaned on custom reference systems as we were already using them for  a bunch of other stuff.
