### ISSUE TITLE
dangling seg/@corresp pointers in acs0000001-03-i098.xml

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/swinburne#4]
I just noticed (but haven't investigated) that acs0000001-03-i098.xml contains multiple <seg> elements whose `@corresp` pointers are dangling. e.g. 
```xml
	<seg corresp="#kw-sea #kw-water" type="keyword" xml:id="k001">
		<w lemma="seamew"><w lemma="sea">sea</w>-<w lemma="mew">mew</w></w>
	</seg>
```

**Comment by jawalsh** [comment]
Bug in generate-component-xinclude-file.xsl.

Need to add another XInclude (like  <xi:include href="authority.xml"
                        xpointer="xmlns(tei=http://www.tei-c.org/ns/1.0) xpath(/tei:TEI/tei:teiHeader/tei:encodingDesc/tei:classDecl/tei:taxonomy)"/>) that adds encodingDesc from processed file (not just authority.xml).

**Comment by Conal-Tuohy** [comment]
I added an `xi:include` element to pull in the `encodingDesc` in revision 3d3fafdb642850e2f632e0b4821ae3acd2985a69, but I see now that it leads to a duplication of some of the content of the `encodingDesc`, since we are pushing some snippets of metadata into both the large transcript files and also the metadata files (the `listPrefixDecl` at least, and there may be more), and then transcluding a copy from both places into the files which make up the individual texts. So some rationalization remains to be done. Probably we should not insert those things into the metadata files, I guess.
